alerts:
  motion_threshold: 0.2
  notification:
    email:
      enabled: true
      recipients:
      - admin@example.com
      smtp_password: your_app_password
      smtp_port: 587
      smtp_server: smtp.gmail.com
      smtp_username: your_email@gmail.com
    sms:
      enabled: false
      phone_numbers:
      - 1234567890
      service: twilio
      twilio_account_sid: your_account_sid
      twilio_auth_token: your_auth_token
      twilio_from_number: 1987654321
  person_loitering_time: 30
analysis:
  algorithm: basic
cameras:
- fps: 25
  loop: true
  name: Camera 1
  type: video
  url: D:\Main EL\vigilance_system\videos\WhatsApp Video 2025-04-22 at 20.45.45_529ae150.mp4
- fps: 25
  loop: true
  name: Camera 2
  type: video
  url: D:\Main EL\vigilance_system\videos\WhatsApp Video 2025-04-22 at 20.47.50_dd1a37f6.mp4
- fps: 25
  loop: true
  name: Camera 3
  type: video
  url: D:\Main EL\vigilance_system\videos\WhatsApp Video 2025-04-22 at 20.48.20_3c3ca36c.mp4
classification:
  algorithm: decision_tree
dashboard:
  authentication:
    enabled: true
    password: change_me_immediately
    username: admin
  debug: false
  host: 0.0.0.0
  port: 5000
  visualizations:
    show_algorithm_steps: true
    show_decision_making: true
    show_stabilization: true
    show_tracking: false
detection:
  classes_of_interest:
  - 0
  - 1
  - 2
  confidence_threshold: 0.5
  device: cuda:0
  model: yolov5s
  nms_threshold: 0.45
logging:
  backup_count: 5
  file: logs/vigilance.log
  level: INFO
  max_size_mb: 10
network:
  frame_rate: 25
  resolution: medium
  routing_algorithm: round_robin
preprocessing:
  denoising:
    enabled: true
    strength: 10
  stabilization:
    enabled: true
    smoothing_radius: 15
tracking:
  algorithm: yolov8
  kalman:
    measurement_noise: 0.1
    process_noise: 0.01
  knn:
    n_neighbors: 3
  max_disappeared: 30
  max_distance: 50.0
  svm:
    C: 1.0
  yolov8:
    confidence_threshold: 0.5
    iou_threshold: 0.3
